In [1]:
import pandas as pd

df = pd.read_csv("Amazon Sale Report.csv")

print(df.shape)
print(df.isnull().sum())

(128975, 24)
index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6872
Qty                       0
currency               7795
Amount                 7795
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         49153
B2B                       0
fulfilled-by          89698
Unnamed: 22           49050
dtype: int64

C:\Users\Samyak\AppData\Local\Temp\ipykernel_20244\3121009156.py:3: DtypeWarning: Columns (23) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("Amazon Sale Report.csv")

In [3]:
df.drop(columns=['Unnamed: 22'], inplace=True)

In [4]:
df.duplicated().sum()

np.int64(0)

In [5]:
df.dtypes

index                   int64
Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
currency               object
Amount                float64
ship-city              object
ship-state             object
ship-postal-code      float64
ship-country           object
promotion-ids          object
B2B                      bool
fulfilled-by           object
dtype: object

In [6]:
df['Date']=pd.to_datetime(df['Date'])

C:\Users\Samyak\AppData\Local\Temp\ipykernel_20244\3023999556.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Date']=pd.to_datetime(df['Date'])

In [10]:
df['Date'].head(50)

0    2022-04-30
1    2022-04-30
2    2022-04-30
3    2022-04-30
4    2022-04-30
5    2022-04-30
6    2022-04-30
7    2022-04-30
8    2022-04-30
9    2022-04-30
10   2022-04-30
11   2022-04-30
12   2022-04-30
13   2022-04-30
14   2022-04-30
15   2022-04-30
16   2022-04-30
17   2022-04-30
18   2022-04-30
19   2022-04-30
20   2022-04-30
21   2022-04-30
22   2022-04-30
23   2022-04-30
24   2022-04-30
25   2022-04-30
26   2022-04-30
27   2022-04-30
28   2022-04-30
29   2022-04-30
30   2022-04-30
31   2022-04-30
32   2022-04-30
33   2022-04-30
34   2022-04-30
35   2022-04-30
36   2022-04-30
37   2022-04-30
38   2022-04-30
39   2022-04-30
40   2022-04-30
41   2022-04-30
42   2022-04-30
43   2022-04-30
44   2022-04-30
45   2022-04-30
46   2022-04-30
47   2022-04-30
48   2022-04-30
49   2022-04-30
Name: Date, dtype: datetime64[ns]

In [13]:
df['Month']=df['Date'].dt.month_name()
df['Month_Num']=df['Date'].dt.month
df['Quarter']=df['Date'].dt.quarter
df['Weekday']=df['Date'].dt.day_name()
df['Year']=df['Date'].dt.year

In [14]:
df[['Date','Month','Month_Num','Quarter','Weekday','Year']].head()

        Date  Month  Month_Num  Quarter   Weekday  Year
0 2022-04-30  April          4        2  Saturday  2022
1 2022-04-30  April          4        2  Saturday  2022
2 2022-04-30  April          4        2  Saturday  2022
3 2022-04-30  April          4        2  Saturday  2022
4 2022-04-30  April          4        2  Saturday  2022

In [15]:
df[df['Amount'].isna()][['Status','Amount']].head(20)

        Status  Amount
8    Cancelled     NaN
29   Cancelled     NaN
65   Cancelled     NaN
84   Cancelled     NaN
95   Cancelled     NaN
101  Cancelled     NaN
132  Cancelled     NaN
139  Cancelled     NaN
155  Cancelled     NaN
165  Cancelled     NaN
205  Cancelled     NaN
215  Cancelled     NaN
242  Cancelled     NaN
249  Cancelled     NaN
250  Cancelled     NaN
271  Cancelled     NaN
328  Cancelled     NaN
363  Cancelled     NaN
381  Cancelled     NaN
413  Cancelled     NaN

In [16]:
df[df['Amount'].isna()]['Status'].value_counts()

Status
Cancelled                       7566
Shipped                          208
Shipped - Delivered to Buyer       8
Shipping                           8
Shipped - Returned to Seller       3
Pending                            2
Name: count, dtype: int64

In [17]:
missing_amount = df[df['Amount'].isna()]

missing_amount[
    missing_amount['Status'] != 'Cancelled'
][['Order ID','Status','Qty','Category']]

                   Order ID   Status  Qty       Category
937     S02-5278980-4327051  Shipped   15         Blouse
1057    S02-9107114-0460608  Shipped    2            Set
1615    405-7790745-1369118  Shipped    0          kurta
1989    171-9673855-2321133  Shipped    0            Set
2424    404-7478762-7926753  Shipped    0            Set
...                     ...      ...  ...            ...
124616  S02-2059602-9568060  Shipped    1          kurta
124617  S02-3811761-8377519  Shipped    2            Set
124619  S02-5216693-3162561  Shipped    1            Set
124621  S02-7324586-1573702  Shipped    1            Set
128085  406-6890147-5272318  Shipped    0  Western Dress

[229 rows x 4 columns]

In [18]:
df_cancelled = df[df['Status'] == 'Cancelled']
df_non_cancelled = df[df['Status'] != 'Cancelled']

In [19]:
df_cancelled['Amount'] = df_cancelled['Amount'].fillna(0)

C:\Users\Samyak\AppData\Local\Temp\ipykernel_20244\3034782748.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cancelled['Amount'] = df_cancelled['Amount'].fillna(0)

In [20]:
df.loc[
    (df['Status'] == 'Cancelled') &
    (df['Amount'].isna()),
    'Amount'
] = 0

In [21]:
df[
    (df['Amount'].isna()) &
    (df['Status'] != 'Cancelled')
]['Status'].value_counts()

Status
Shipped                         208
Shipped - Delivered to Buyer      8
Shipping                          8
Shipped - Returned to Seller      3
Pending                           2
Name: count, dtype: int64

In [22]:
df[
    (df['Amount'].isna()) &
    (df['Status'] != 'Cancelled')
][['Order ID','Status','Qty','Category','currency']].head(20)

                 Order ID   Status  Qty Category currency
937   S02-5278980-4327051  Shipped   15   Blouse      NaN
1057  S02-9107114-0460608  Shipped    2      Set      NaN
1615  405-7790745-1369118  Shipped    0    kurta      NaN
1989  171-9673855-2321133  Shipped    0      Set      NaN
2424  404-7478762-7926753  Shipped    0      Set      NaN
2819  404-0814480-8157169  Shipped    0    kurta      NaN
3631  S02-1006261-5356758  Shipped    9    kurta      NaN
3632  S02-3681731-6111841  Shipped    1    kurta      NaN
3634  S02-1926028-4838217  Shipped    1    kurta      NaN
3636  S02-6828927-1180856  Shipped   13    kurta      NaN
3637  S02-3409426-0744131  Shipped    2   Blouse      NaN
3886  S02-8357726-8633940  Shipped    1      Set      NaN
3887  S02-6358630-3384547  Shipped    1   Blouse      NaN
3888  S02-8920429-3367507  Shipped    1      Set      NaN
3889  S02-0827522-8659612  Shipped    1      Set      NaN
3890  S02-7924344-3280541  Shipped    1    kurta      NaN
3891  S02-7832149-5714447  Shipped    1    kurta      NaN
3892  S02-9649067-3246849  Shipped    1    kurta      NaN
3893  S02-2310917-8166336  Shipped    1    kurta      NaN
3894  S02-0668744-7285638  Shipped    1      Set      NaN

In [23]:
df[
    (df['Amount'].isna()) &
    (df['currency'].isna())
].shape

(229, 28)

In [24]:
df = df[
    ~(
        (df['Amount'].isna()) &
        (df['currency'].isna()) &
        (df['Status'] != 'Cancelled')
    )
]

In [26]:
df.isna().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status         6861
Qty                       0
currency               7566
Amount                    0
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         48995
B2B                       0
fulfilled-by          89480
Month                     0
Month_Num                 0
Quarter                   0
Weekday                   0
Year                      0
dtype: int64

In [27]:
df[df['Courier Status'].isna()]['Status'].value_counts()

Status
Cancelled    6861
Name: count, dtype: int64

In [29]:
df.loc[
    (df['Status']=='Cancelled') &
    (df['Courier Status'].isna()),
    'Courier Status'
]='Not Shipped'

In [30]:
df.isna().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status            0
Qty                       0
currency               7566
Amount                    0
ship-city                33
ship-state               33
ship-postal-code         33
ship-country             33
promotion-ids         48995
B2B                       0
fulfilled-by          89480
Month                     0
Month_Num                 0
Quarter                   0
Weekday                   0
Year                      0
dtype: int64

In [31]:
df['fulfilled-by'].value_counts(dropna=False)

fulfilled-by
NaN          89480
Easy Ship    39266
Name: count, dtype: int64

In [33]:
pd.crosstab(df['Fulfilment'],df['fulfilled-by'],dropna=False)

fulfilled-by  Easy Ship    NaN
Fulfilment
Amazon                0  89480
Merchant          39266      0

In [34]:
df[df['ship-city'].isna()][
    ['Status','ship-city','ship-state','ship-country']
]

                              Status ship-city ship-state ship-country
1871                         Shipped       NaN        NaN          NaN
1872                         Shipped       NaN        NaN          NaN
8752                         Shipped       NaN        NaN          NaN
11215                        Shipped       NaN        NaN          NaN
13252                      Cancelled       NaN        NaN          NaN
15688                        Shipped       NaN        NaN          NaN
16787   Shipped - Delivered to Buyer       NaN        NaN          NaN
18351                        Shipped       NaN        NaN          NaN
22930   Shipped - Returned to Seller       NaN        NaN          NaN
24986                      Cancelled       NaN        NaN          NaN
30379   Shipped - Delivered to Buyer       NaN        NaN          NaN
37963                      Cancelled       NaN        NaN          NaN
37964                      Cancelled       NaN        NaN          NaN
60986   Shipped - Delivered to Buyer       NaN        NaN          NaN
63040                        Shipped       NaN        NaN          NaN
73675   Shipped - Delivered to Buyer       NaN        NaN          NaN
73746                        Shipped       NaN        NaN          NaN
73771                        Shipped       NaN        NaN          NaN
73772                        Shipped       NaN        NaN          NaN
73911                      Cancelled       NaN        NaN          NaN
80011   Shipped - Returned to Seller       NaN        NaN          NaN
80092                        Shipped       NaN        NaN          NaN
80455   Shipped - Delivered to Buyer       NaN        NaN          NaN
84008   Shipped - Returned to Seller       NaN        NaN          NaN
84757                        Shipped       NaN        NaN          NaN
104201  Shipped - Delivered to Buyer       NaN        NaN          NaN
106498                     Cancelled       NaN        NaN          NaN
124215                     Cancelled       NaN        NaN          NaN
124357                       Shipped       NaN        NaN          NaN
124358                       Shipped       NaN        NaN          NaN
124359                       Shipped       NaN        NaN          NaN
125385                       Shipped       NaN        NaN          NaN
126620  Shipped - Delivered to Buyer       NaN        NaN          NaN

In [35]:
df = df.dropna(
    subset=[
        'ship-city',
        'ship-state',
        'ship-postal-code',
        'ship-country'
    ]
)

In [36]:
df['Promotion_Used'] = df['promotion-ids'].notna()

C:\Users\Samyak\AppData\Local\Temp\ipykernel_20244\1781862683.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Promotion_Used'] = df['promotion-ids'].notna()

In [38]:
df['promotion-ids'].head()

0                                                  NaN
1    Amazon PLCC Free-Financing Universal Merchant ...
2         IN Core Free Shipping 2015/04/08 23-48-5-108
3                                                  NaN
4                                                  NaN
Name: promotion-ids, dtype: object

In [39]:
df.to_csv('amazon_sales_clean.csv',index=False)

In [40]:
df.isna().sum()

index                     0
Order ID                  0
Date                      0
Status                    0
Fulfilment                0
Sales Channel             0
ship-service-level        0
Style                     0
SKU                       0
Category                  0
Size                      0
ASIN                      0
Courier Status            0
Qty                       0
currency               7564
Amount                    0
ship-city                 0
ship-state                0
ship-postal-code          0
ship-country              0
promotion-ids         48987
B2B                       0
fulfilled-by          89460
Month                     0
Month_Num                 0
Quarter                   0
Weekday                   0
Year                      0
Promotion_Used            0
dtype: int64